cmake_minimum_required(VERSION 3.16)
project(WorkerTests LANGUAGES CXX)
enable_testing()
find_package(Threads REQUIRED)
add_executable(worker-tests main.cpp ../../common/utils/workers.cpp ../../lib/Tempest/Engine/utility/cputrace.cpp)
target_compile_features(worker-tests PRIVATE cxx_std_20)
target_compile_definitions(worker-tests PRIVATE NOMINMAX)
target_include_directories(worker-tests PRIVATE ../../common ../../lib/Tempest/Engine/include)
target_link_libraries(worker-tests PRIVATE Threads::Threads)
if(ANDROID)
  target_link_libraries(worker-tests PRIVATE android)
endif()
add_test(NAME workers-completion COMMAND worker-tests)
set_tests_properties(workers-completion PROPERTIES TIMEOUT 60)
